### ISSUE TITLE
[Low-priority] Missing newline on pretty-printing

### ISSUE THREAD

**Issue by mratsim** [protolambda/zcli#2]
Not sure if it's in zcli or zssz but pretty-printing is missing a new line.

![DeepinScreenshot_select-area_20190924163520](https://user-images.githubusercontent.com/22738317/65521393-7436b780-dee9-11e9-8b05-4c711c119c72.png)

**Comment by protolambda** [comment]
Ah yes, will fix that, thanks

**Comment by protolambda** [comment]
Updated, see https://github.com/protolambda/zcli/releases/tag/v0.0.12
