### ISSUE TITLE
Deadlock in zcli genesis mock on Linux

### ISSUE THREAD

**Issue by mratsim** [protolambda/zcli#3]
On Linux with latest go. zcli v0.0.11 also deadlocks.

![DeepinScreenshot_select-area_20191001132752](https://user-images.githubusercontent.com/22738317/65958264-4b657380-e44f-11e9-8bfb-3f1b12addc6c.png)

**Comment by protolambda** [comment]
It's not a deadlock, it's waiting for you to pipe in keys in std-in. There's also a key generation command, or use the key files from the pm repo.

**Comment by mratsim** [comment]
oh, it changed then, in the past I had something similar to this output (iirc I cleaned that up but I didn't need to input keys):

https://github.com/status-im/nim-beacon-chain/pull/406/files#diff-b8923d2c0ad820dab61c22d5b6b2475aR44-R107

**Comment by protolambda** [comment]
The previous mock required keys to be read from a file. That still works, it just falls back on std-in when no key file source is specified. Also check out the other command args ("RTFM" :stuck_out_tongue_winking_eye: `--help`).
