### ISSUE TITLE
`zcli genesis mock` hangs

### ISSUE THREAD

**Issue by JustinDrake** [protolambda/zcli#4]
I left it running for about 1 hour before killing it—looks like it hung. What is the expected runtime?

![Screenshot 2020-07-07 at 15 50 50](https://user-images.githubusercontent.com/731743/86799268-ad4fab00-c069-11ea-9860-b9569e55f44d.png)

**Comment by protolambda** [comment]
Expected runtime is a few seconds at most. If something takes more than that anywhere in ZCLI let me know, it's either a bug, or a usage problem.

Here though, it's a usage problem. To generate a genesis state, it expects a list of validator keys to be piped into STDIN. If it can't read anything, it will just hang, waiting for the input.
Alternatively, if you can't use STDIN, you can use `--keys` to read them from a file.

And then there's `zcli keys generate` (with options) to generate a keys file with random keys.

Each command has a `--help` that explains it, but agree that an unused STDIN causing a hang is a bit of a gotcha.

These are all utilities from the interop-lockin times (canada), but should still work. If not, let me know and I'll fix it.
